/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.21.0
 */

declare export function hello(who?: string): string;

export * from './index.js'; export * from './index.ts';
